version: '3.8'

services:
  go-tsdb:
    build:
      context: .
      dockerfile: deployment/docker/go/Dockerfile
    ports:
      - "9090:9090"  # Prometheus API
      - "9091:9091"  # Remote write API
    volumes:
      - ./data/go:/data
    environment:
      - TSDB_STORAGE_PATH=/data

  cpp-tsdb:
    build:
      context: .
      dockerfile: deployment/docker/cpp/Dockerfile
    ports:
      - "9092:9090"  # Prometheus API
      - "9093:9091"  # Remote write API
    volumes:
      - ./data/cpp:/data
    environment:
      - TSDB_STORAGE_PATH=/data

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9094:9090"
    volumes:
      - ./deployment/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./deployment/grafana:/etc/grafana/provisioning
    depends_on:
      - go-tsdb
      - cpp-tsdb
      - prometheus 