if(EXISTS "/Users/vobbilis/go/src/github.com/vobbilis/codegen/mytsdb/test/stress/tsdb_data_volume_stress_test[1]_tests.cmake")
  include("/Users/vobbilis/go/src/github.com/vobbilis/codegen/mytsdb/test/stress/tsdb_data_volume_stress_test[1]_tests.cmake")
else()
  add_test(tsdb_data_volume_stress_test_NOT_BUILT tsdb_data_volume_stress_test_NOT_BUILT)
endif()
