if(EXISTS "/Users/vobbilis/go/src/github.com/vobbilis/codegen/mytsdb/test/load/tsdb_load_tests[1]_tests.cmake")
  include("/Users/vobbilis/go/src/github.com/vobbilis/codegen/mytsdb/test/load/tsdb_load_tests[1]_tests.cmake")
else()
  add_test(tsdb_load_tests_NOT_BUILT tsdb_load_tests_NOT_BUILT)
endif()
