if(EXISTS "/Users/vobbilis/go/src/github.com/vobbilis/codegen/mytsdb/test/load/tsdb_sustained_load_test[1]_tests.cmake")
  include("/Users/vobbilis/go/src/github.com/vobbilis/codegen/mytsdb/test/load/tsdb_sustained_load_test[1]_tests.cmake")
else()
  add_test(tsdb_sustained_load_test_NOT_BUILT tsdb_sustained_load_test_NOT_BUILT)
endif()
