if(EXISTS "/Users/vobbilis/go/src/github.com/vobbilis/codegen/mytsdb/test/scalability/tsdb_horizontal_scalability_test[1]_tests.cmake")
  include("/Users/vobbilis/go/src/github.com/vobbilis/codegen/mytsdb/test/scalability/tsdb_horizontal_scalability_test[1]_tests.cmake")
else()
  add_test(tsdb_horizontal_scalability_test_NOT_BUILT tsdb_horizontal_scalability_test_NOT_BUILT)
endif()
