if(EXISTS "/Users/vobbilis/go/src/github.com/vobbilis/codegen/mytsdb/test/unit/tsdb_atomic_metrics_unit_tests[1]_tests.cmake")
  include("/Users/vobbilis/go/src/github.com/vobbilis/codegen/mytsdb/test/unit/tsdb_atomic_metrics_unit_tests[1]_tests.cmake")
else()
  add_test(tsdb_atomic_metrics_unit_tests_NOT_BUILT tsdb_atomic_metrics_unit_tests_NOT_BUILT)
endif()
