if(EXISTS "/Users/vobbilis/go/src/github.com/vobbilis/codegen/mytsdb/test/integration/tsdb_multi_component_test[1]_tests.cmake")
  include("/Users/vobbilis/go/src/github.com/vobbilis/codegen/mytsdb/test/integration/tsdb_multi_component_test[1]_tests.cmake")
else()
  add_test(tsdb_multi_component_test_NOT_BUILT tsdb_multi_component_test_NOT_BUILT)
endif()
