if(EXISTS "/Users/vobbilis/go/src/github.com/vobbilis/codegen/mytsdb/test/integration/tsdb_core_storage_integration_test[1]_tests.cmake")
  include("/Users/vobbilis/go/src/github.com/vobbilis/codegen/mytsdb/test/integration/tsdb_core_storage_integration_test[1]_tests.cmake")
else()
  add_test(tsdb_core_storage_integration_test_NOT_BUILT tsdb_core_storage_integration_test_NOT_BUILT)
endif()
